// src/components/TilesheetCanvas.vue
<script setup lang="ts">
import { inject, onMounted, onUpdated, ref, watchEffect } from "vue";
import { DatasBin } from "../lib/datas-bin";
import { DatasBinKey } from "../useDatasBin";

const props = defineProps<{ imageData: ImageData; scale: number }>();

inject(DatasBinKey);
const canvasWidth = 256;
const canvasHeight = 256 * 6;
const canvasRef = ref<HTMLCanvasElement | null>(null);

watchEffect(() => {
  if (!props.imageData || !canvasRef.value) {
    return;
  }

  draw(canvasRef.value.getContext("2d")!, props.imageData);
});

function draw(ctx: CanvasRenderingContext2D, imageData: ImageData) {
  ctx.clearRect(0, 0, canvasWidth, canvasHeight);
  ctx.putImageData(imageData, 0, 0);
}
</script>

<template>
  <div class="flex flex-col justify-center">
    <div class="">
      <canvas
        ref="canvasRef"
        :width="canvasWidth"
        :height="canvasHeight"
        tabindex="0"
        class="canvas"
        :style="{ transform: `scale(${scale + 1})` }"
      ></canvas>
    </div>
  </div>
</template>

<style scoped>
canvas {
  transform-origin: left top;
}
</style>

// src/components/TilesheetCanvas.tsx
import { useRef, useEffect } from "react";

interface TilesheetCanvasProps {
  imageData: ImageData;
  scale: number;
}

const TilesheetCanvas = ({ imageData, scale }: TilesheetCanvasProps) => {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const canvasWidth = 256;
  const canvasHeight = 256 * 6;

  useEffect(() => {
    if (!imageData || !canvasRef.current) {
      return;
    }

    const ctx = canvasRef.current.getContext("2d");
    if (ctx) {
      draw(ctx, imageData);
    }
  }, [imageData]);

  function draw(ctx: CanvasRenderingContext2D, imageData: ImageData) {
    ctx.clearRect(0, 0, canvasWidth, canvasHeight);
    ctx.putImageData(imageData, 0, 0);
  }

  return (
    <div className="flex flex-col justify-center">
      <div className="">
        <canvas
          ref={canvasRef}
          width={canvasWidth}
          height={canvasHeight}
          tabIndex={0}
          className="canvas"
          style={{ transform: `scale(${scale + 1})`, transformOrigin: 'left top' }}
        ></canvas>
      </div>
    </div>
  );
};

export default TilesheetCanvas;
